
defaults: &defaults
  working_directory: ~/react-resizable-box
  docker:
    - image: quramy/node-nightmare
      environment:
        DISPLAY: ":99"

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Lint
          command: yarn run lint
      - run:
          name: Test
          command: yarn run test
  deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - add-ssh-keys:
          fingerprints:
            - "7c:17:bc:7b:8a:a2:ef:6b:11:f3:56:a0:ac:15:4c:9a"          
      - run:
          name: Setup git
          command: |
            git config --global user.email "bokuweb12@gmail.com"
            git config --global user.name "bokuweb"          
      - run:
          name: Deploy
          filters:
            branches:
              only: master
          command: yarn run deploy                   
  patch_release:
    <<: *defaults
    steps:
      - add-ssh-keys:
          fingerprints:
            - "7c:17:bc:7b:8a:a2:ef:6b:11:f3:56:a0:ac:15:4c:9a"
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build
          command: yarn run build
      - run:
          name: Setup git
          command: |
            git config --global user.email "bokuweb12@gmail.com"
            git config --global user.name "bokuweb"
      - run:
          name: Login npm
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
            npm whoami
      - run:
          name: Publish to npm
          command: |
            sh deploy-patch.sh
  minor_release:
    <<: *defaults
    steps:
      - add-ssh-keys:
          fingerprints:
            - "7c:17:bc:7b:8a:a2:ef:6b:11:f3:56:a0:ac:15:4c:9a"
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build
          command: yarn run build          
      - run:
          name: Setup git
          command: |
            git config --global user.email "bokuweb12@gmail.com"
            git config --global user.name "bokuweb"
      - run:
          name: Login npm
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
            npm whoami
      - run:
          name: Publish to npm
          command: |
            sh deploy-minor.sh
workflows:
  version: 2
  build_pipeline:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only: master
      - confirm_patch:
          type: approval
          filters:
            branches:
              only: master
          requires:
            - build
      - confirm_minor:
          type: approval
          filters:
            branches:
              only: master
          requires:
            - build
      - patch_release:
          filters:
            branches:
              only: master
          requires:
            - confirm_patch
      - minor_release:
          filters:
            branches:
              only: master
          requires:
            - confirm_minor
